version: '3'
services:
  app:
    build:
      context: .
    container_name: "buscabelo"
    working_dir: "/usr/src/app"
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3000"
