version: '3'
services:
  app:
    build:
      context: .
    container_name: "buscabelo"
    working_dir: "/usr/src/app"
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - app