name: 'Notificação de Atualização'

on:
  push:
    branches:
      - master

jobs:
  notify:
    name: 'Notificando repositório guarda-chuva'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Envio de Notificação
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          PARENT_REPO: tads-cnat/buscabelo
          PARENT_BRANCH: main
          WORKFLOW_ID: 19756432
        run: |
          curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{ "ref": "${{ env.PARENT_BRANCH }}", "inputs": { "module": "front" }}'
